1-PyTorch 是什么?

是一个基于Python的科学计算包，目标用户有两类:

* 为了使用GPU来替代numpy
* 一个深度学习研究平台：提供最大的灵活性和速度

In [1]:
# 张量(Tensors) 张量类似于numpy的ndarrays ，不同之处在于张量可以使用GPU来加快运算

In [2]:
from __future__ import print_function

In [3]:
import torch

In [4]:
# 构建一个未初始化的5*3的矩阵：

In [5]:
x = torch.Tensor(5,3)

In [6]:
x

tensor([[0.0000e+00, -0.0000e+00, 1.3805e+17],
        [1.5849e+29, 1.0588e-22, 1.4013e-45],
        [1.0970e-22, 1.4013e-45, 1.0970e-22],
        [1.4013e-45, 1.0626e-22, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
# 构建一个零矩阵，使用long的类型
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
# 从数据中直接构建一个张量(tensor)：
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [9]:
# 或者在已有的张量(tensor)中构建一个张量(tensor). 
# 这些方法将重用输入张量(tensor)的属性，
# 例如， dtype，除非用户提供新值

In [10]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[ 0.8913, -0.2885, -1.0347],
        [-1.0029,  0.5271,  0.3682],
        [ 1.5519,  0.1200,  0.0802],
        [ 0.8384, -0.3075, -0.5456],
        [ 0.2258, -1.7734,  0.4377]])

In [12]:
#  上面的是覆盖索引

In [13]:
# 获取张量(tensor)的大小
x.size()

torch.Size([5, 3])

In [14]:
y = torch.rand(5,3)
x + y

tensor([[ 1.8633,  0.1339, -0.8699],
        [-0.3558,  1.4065,  0.4760],
        [ 2.3959,  0.3906,  0.4319],
        [ 0.9233,  0.1385, -0.2207],
        [ 0.5166, -1.1073,  0.6956]])

In [15]:
y

tensor([[0.9721, 0.4224, 0.1648],
        [0.6471, 0.8795, 0.1078],
        [0.8440, 0.2706, 0.3517],
        [0.0849, 0.4460, 0.3248],
        [0.2908, 0.6661, 0.2578]])

In [16]:
x

tensor([[ 0.8913, -0.2885, -1.0347],
        [-1.0029,  0.5271,  0.3682],
        [ 1.5519,  0.1200,  0.0802],
        [ 0.8384, -0.3075, -0.5456],
        [ 0.2258, -1.7734,  0.4377]])

In [17]:
torch.add(x,y)

tensor([[ 1.8633,  0.1339, -0.8699],
        [-0.3558,  1.4065,  0.4760],
        [ 2.3959,  0.3906,  0.4319],
        [ 0.9233,  0.1385, -0.2207],
        [ 0.5166, -1.1073,  0.6956]])

In [18]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[ 1.8633,  0.1339, -0.8699],
        [-0.3558,  1.4065,  0.4760],
        [ 2.3959,  0.3906,  0.4319],
        [ 0.9233,  0.1385, -0.2207],
        [ 0.5166, -1.1073,  0.6956]])

In [19]:
y.add_(x)

tensor([[ 1.8633,  0.1339, -0.8699],
        [-0.3558,  1.4065,  0.4760],
        [ 2.3959,  0.3906,  0.4319],
        [ 0.9233,  0.1385, -0.2207],
        [ 0.5166, -1.1073,  0.6956]])

任何在原地(in-place)改变张量的操作都有一个_后缀。
例如x.copy_(y), x.t_()操作将改变x.
你可以使用所有的numpy索引操作。
你可以使用各种类似标准NumPy的花哨的索引功能

In [20]:
# 调整大小：如果要调整张量/重塑张量，可以使用torch.view：
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
x.size(),y.size(),z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [22]:
# 如果你有一个单元素张量，使用.item()将值作为Python数字
x = torch.randn(1)
x,x.item()

(tensor([-0.5195]), -0.5194719433784485)

In [23]:
# 把Torch张量转换为numpy数组

In [24]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [25]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [26]:
type(b)

numpy.ndarray

In [27]:
# 把numpy数组转换为torch张量

In [28]:
import numpy as np

In [29]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
a,b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [30]:
a

array([2., 2., 2., 2., 2.])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
# cuda张量，可以使用.to方法将张量移动到任何设备上

In [33]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    

In [34]:
z

tensor([[ 0.1409, -0.0404, -0.4595, -1.0628,  0.1642, -1.7079, -0.7659, -0.6554],
        [ 2.0671, -0.3203, -0.4876, -0.2249,  0.4675,  0.9631, -0.3451, -0.3972]])

In [35]:
z.to("cpu",torch.double)

tensor([[ 0.1409, -0.0404, -0.4595, -1.0628,  0.1642, -1.7079, -0.7659, -0.6554],
        [ 2.0671, -0.3203, -0.4876, -0.2249,  0.4675,  0.9631, -0.3451, -0.3972]],
       dtype=torch.float64)